language: haskell

ghc: 7.8

before_install:
    - |
      curl -L https://get.rvm.io | bash -s stable --ruby --gems='rspec'
      source /home/travis/.rvm/scripts/rvm
      bash <(curl -sS https://nixos.org/nix/install)
      source $HOME/.nix-profile/etc/profile.d/nix.sh
      hash -r

install:
    - nix-shell --run 'cabal test && rspec'

script: true
