language: haskell

ghc:
    - 7.8
    - 7.6

before_install:
    - git clone https://github.com/supki/temporary
    - cabal install temporary/temporary.cabal
    - cabal install alex
    - cabal install happy
    - cabal install c2hs
